_: !include version.yaml

name:             hspec
version: *version
copyright:
  - (c) 2011-2023 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
maintainer:       Simon Hengel <sol@typeful.net>
category:         Testing
stability:        experimental
homepage:         https://hspec.github.io/
synopsis:         A Testing Framework for Haskell
description: |
  Hspec is a testing framework for Haskell.  Some of Hspec's distinctive
  features are:

  * a friendly DSL for defining tests

  * integration with QuickCheck, SmallCheck, and HUnit

  * parallel test execution

  * automatic discovery of test files

  The Hspec Manual is at <https://hspec.github.io/>.

extra-source-files:
  - version.yaml
  - CHANGES.markdown

github: hspec/hspec

ghc-options: -Wall


dependencies:
  base: 4.*
  hspec-core: *version
  hspec-discover: *version
  hspec-expectations: 0.8.2.*
  QuickCheck: ">= 2.12"

library:
  source-dirs: src
  exposed-modules:
    - Test.Hspec
    - Test.Hspec.Discover
    - Test.Hspec.Formatters
    - Test.Hspec.QuickCheck
    - Test.Hspec.Runner
