name:             hspec
version:          2.7.4
copyright:
  - (c) 2011-2019 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
maintainer:       Simon Hengel <sol@typeful.net>
category:         Testing
stability:        experimental
homepage:         http://hspec.github.io/
synopsis:         A Testing Framework for Haskell
description: |
  Hspec is a testing framework for Haskell.  Some of Hspec's distinctive
  features are:

  * a friendly DSL for defining tests

  * integration with QuickCheck, SmallCheck, and HUnit

  * parallel test execution

  * automatic discovery of test files

  The Hspec Manual is at <http://hspec.github.io/>.

extra-source-files: CHANGES.markdown

github: hspec/hspec

ghc-options: -Wall

dependencies:
  - base == 4.*
  - hspec-core == 2.7.4
  - hspec-discover == 2.7.4
  - hspec-expectations == 0.8.2.*
  - QuickCheck >= 2.12

library:
  source-dirs: src
  exposed-modules:
    - Test.Hspec
    - Test.Hspec.Discover
    - Test.Hspec.Formatters
    - Test.Hspec.QuickCheck
    - Test.Hspec.Runner
