name:             hspec-meta
version:          2.3.0
license:          MIT
copyright:
  - (c) 2011-2015 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
maintainer:       Simon Hengel <sol@typeful.net>
category:         Testing
stability:        experimental
bug-reports:      https://github.com/hspec/hspec/issues
homepage:         http://hspec.github.io/
synopsis:         A version of Hspec which is used to test Hspec itself
description: |
  A stable version of Hspec which is used to test the
  in-development version of Hspec.

extra-source-files: changelog

github: hspec/hspec

ghc-options: -Wall

dependencies:
  - base == 4.*
  - hspec-core == 2.3.0
  - hspec-discover == 2.3.0
  - hspec-expectations == 0.8.0.*
  - transformers >= 0.2.2.0
  - QuickCheck >= 2.5.1
  - HUnit >= 1.2.5
  - call-stack

library:
  source-dirs: src
  dependencies:
  exposed-modules:
    - Test.Hspec
    - Test.Hspec.Core
    - Test.Hspec.Discover
    - Test.Hspec.Formatters
    - Test.Hspec.HUnit
    - Test.Hspec.QuickCheck
    - Test.Hspec.Runner
