<<: !include version.yaml

name: hspec
github: hspec/hspec
copyright:
  - (c) 2011-2024 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
description: |
  Hspec is a testing framework for Haskell.  Some of Hspec's distinctive
  features are:

  * a friendly DSL for defining tests

  * integration with QuickCheck, SmallCheck, and HUnit

  * parallel test execution

  * automatic discovery of test files

  The Hspec Manual is at <https://hspec.github.io/>.

extra-source-files:
  - version.yaml
  - CHANGES.markdown

ghc-options: -Wall

dependencies:
  base: 4.*
  hspec-core: *version
  hspec-discover: *version
  hspec-expectations: 0.8.4.*
  QuickCheck: ">= 2.12"

library:
  source-dirs: src
  exposed-modules:
    - Test.Hspec
    - Test.Hspec.Discover
    - Test.Hspec.Formatters
    - Test.Hspec.QuickCheck
    - Test.Hspec.Runner
