name: hspec-contrib
version: 0.5.1.1
copyright:
  - (c) 2011-2022 Simon Hengel
  - (c) 2014 Junji Hashimoto
maintainer: Simon Hengel <sol@typeful.net>
category: Testing
stability: experimental
homepage: http://hspec.github.io/
synopsis: Contributed functionality for Hspec
description: Contributed functionality for Hspec

github: hspec/hspec/hspec-contrib

ghc-options: -Wall

dependencies:
  - base == 4.*
  - hspec-core >= 2.5.0
  - HUnit

library:
  source-dirs: src
tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec-core >= 2.6.0
      - hspec-contrib
      - hspec
      - QuickCheck
    build-tools: hspec-discover
