liquid:
  error_mode: strict

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - css/use.less
  - css/pygments.less
  - css/pygments.trac.less
  - tinc.yaml
  - README.markdown
  - vendor
  - bundle

highlighter: pygments

markdown: redcarpet

redcarpet:
  extensions:
    - with_toc_data
