liquid:
  error_mode: strict

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - css/use.less
  - css/pygments.less
  - css/pygments.trac.less
  - README.markdown
  - bundle
  - bin
  - vendor

highlighter: pygments

markdown: redcarpet

redcarpet:
  extensions:
    - with_toc_data
