source 'https://rubygems.org'
gem 'redcarpet'
gem 'RedCloth'
gem 'jekyll'

gem 'pygments.rb', git: 'https://github.com/hspec/pygments.rb', :tag => 'v1.1.2-hspec'

gem "therubyracer" # required by less

gem 'jekyll-less', git: 'https://github.com/sfi0zy/jekyll-less'
