#!/bin/bash
set -o nounset
set -o errexit

old=CHANGES.markdown
new=$old.new

echo "## Changes in $(cat version.yaml | sed 's/&version //') ($(date -uI))" > $new
cat changes/* >> $new
echo >> $new
cat $old >> $new

mv $new $old

git rm changes/*
