#!/bin/bash
set -o nounset
set -o errexit

old=CHANGES.markdown
new=$old.new

echo "## Changes in $(grep '^version:' version.yaml | cut -d ' ' -f3) ($(date -uI))" > $new
cat changes/* >> $new
echo >> $new
cat $old >> $new

mv $new $old

git rm changes/*
