<<: !include version.yaml

name: hspec-discover
github: hspec/hspec/hspec-discover
copyright: (c) 2012-2023 Simon Hengel
author: Simon Hengel <sol@typeful.net>
synopsis: Automatically discover and run Hspec tests
description: |
  Automatically discover and run Hspec tests

  <https://hspec.github.io/hspec-discover.html>

extra-source-files:
  - version.yaml

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base >= 4.5.0.0 && < 5
  - filepath
  - directory

library:
  source-dirs: src
  exposed: no

executables:
  hspec-discover:
    main: hspec-discover.hs
    source-dirs:
      - driver
    dependencies:
      - hspec-discover

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      hspec-discover:
      hspec-meta: *version
      QuickCheck: ">= 2.7"
      mockery: ">= 0.3.5"
    build-tools: hspec-meta:hspec-meta-discover
