name:             hspec-discover
version:          2.7.4
copyright:        (c) 2012-2019 Simon Hengel
author:           Simon Hengel <sol@typeful.net>
maintainer:       Simon Hengel <sol@typeful.net>
category:         Testing
stability:        experimental
homepage:         http://hspec.github.io/
synopsis:         Automatically discover and run Hspec tests
description: |
  Automatically discover and run Hspec tests

  <http://hspec.github.io/hspec-discover.html>

github: hspec/hspec/hspec-discover

extra-source-files:
  - test-data/**/*.hs
  - test-data/**/.placeholder

ghc-options: -Wall

dependencies:
  - base == 4.*
  - filepath
  - directory

library:
  source-dirs: src
  exposed: no

executables:
  hspec-discover:
    main: hspec-discover.hs
    source-dirs:
      - driver
    dependencies:
      - hspec-discover

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec-discover
      - hspec-meta >= 2.3.2
      - QuickCheck >= 2.7
    build-tools: hspec-meta:hspec-meta-discover
