<<: !include version.yaml

name: hspec-api
github: hspec/hspec/hspec-api
copyright: (c) 2022-2023 Simon Hengel
description: >
  This package provides a stable API that can be used to extend Hspec's
  functionality.
stability: stable

extra-source-files:
  - version.yaml

ghc-options: -Wall

dependencies:
  base: 4.*
  transformers:
  hspec-core: *version

library:
  source-dirs:
    - src
  other-modules:
    - Test.Hspec.Api.Format.V1.Internal
    - Test.Hspec.Api.Format.V2.Config

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - transformers
      - hspec-api
