_: !include version.yaml

name: hspec-api
version: *version
synopsis: A Testing Framework for Haskell
description: >
  This package provides a stable API that can be used to extend Hspec's
  functionality.
copyright: (c) 2022-2023 Simon Hengel
maintainer: Simon Hengel <sol@typeful.net>
category: Testing
stability: stable
homepage: https://hspec.github.io/

github: hspec/hspec/hspec-api

extra-source-files:
  - version.yaml

ghc-options: -Wall

dependencies:
  base: 4.*
  transformers:
  hspec-core: *version

library:
  source-dirs:
    - src
  other-modules:
    - Test.Hspec.Api.Format.V1.Internal

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - transformers
      - hspec-api
