name: hspec-api
version: 0.0.0
synopsis: A Testing Framework for Haskell
description: >
  This package provides a stable API that can be used to extend Hspec's
  functionality.
copyright: (c) 2022-2023 Simon Hengel
maintainer: Simon Hengel <sol@typeful.net>
category: Testing
stability: stable
homepage: https://hspec.github.io/

github: hspec/hspec/hspec-api

ghc-options: -Wall

dependencies:
  - base == 4.*
  - hspec-core >= 2.8.0 && < 2.11.0

library:
  source-dirs:
    - src

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - hspec-api
