_: !include version.yaml

name: hspec-core
version: *version
synopsis: A Testing Framework for Haskell
description: >
  This package exposes internal types and functions that can be used to extend
  Hspec's functionality.
copyright:
  - (c) 2011-2022 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
maintainer: Simon Hengel <sol@typeful.net>
category: Testing
stability: experimental
homepage: http://hspec.github.io/

github: hspec/hspec/hspec-core

extra-source-files:
  - version.yaml
  - help.txt

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base >= 4.5.0.0 && < 5
  - random
  - tf-random
  - setenv
  - ansi-terminal >= 0.6.2
  - time
  - transformers >= 0.2.2.0
  - deepseq
  - HUnit == 1.6.*
  - QuickCheck >= 2.13.1
  - quickcheck-io >= 0.2.0
  - hspec-expectations == 0.8.2.*
  - call-stack >= 0.2.0
  - directory
  - filepath
  - process

  - array # for Diff

when:
  condition: impl(ghc >= 8.2.1)
  dependencies:
    - ghc
    - ghc-boot-th

source-dirs:
  - src
  - vendor

_common:
  - &stm
    when:
      condition: impl(ghc >= 8.4.1)
      then:
        dependencies: stm >= 2.2
      else:
        source-dirs: vendor/stm-2.5.0.1/
        other-modules: Control.Concurrent.STM.TMVar

library:
  <<: *stm
  exposed-modules:
    - Test.Hspec.Core.Spec
    - Test.Hspec.Core.Hooks
    - Test.Hspec.Core.Runner
    - Test.Hspec.Core.Format
    - Test.Hspec.Core.Formatters
    - Test.Hspec.Core.Formatters.V1
    - Test.Hspec.Core.Formatters.V2
    - Test.Hspec.Core.QuickCheck
    - Test.Hspec.Core.Util

tests:
  spec:
    <<: *stm
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec-meta == 2.10.5
      - silently >= 1.2.4
      - QuickCheck >= 2.14
      - process
      - temporary
      - base-orphans
    build-tools: hspec-meta:hspec-meta-discover
