<<: !include version.yaml

name: hspec-core
github: hspec/hspec/hspec-core
copyright:
  - (c) 2011-2023 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
description: >
  This package exposes internal types and functions that can be used to extend
  Hspec's functionality.

extra-source-files:
  - version.yaml
  - help.txt

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base >= 4.8.2.0 && < 5
  - containers
  - random
  - tf-random
  - ansi-terminal >= 0.6.2
  - time
  - transformers >= 0.2.2.0
  - deepseq
  - HUnit == 1.6.*
  - QuickCheck >= 2.13.1
  - quickcheck-io >= 0.2.0
  - hspec-expectations == 0.8.4.*
  - call-stack >= 0.2.0
  - directory
  - filepath
  - process
  - haskell-lexer

  - array # for Diff

source-dirs:
  - src
  - vendor

when:
  condition: impl(ghc >= 8.4.1)
  then:
    dependencies: stm >= 2.2
  else:
    source-dirs: vendor/stm-2.5.0.1/

library:
  exposed-modules:
    - Test.Hspec.Core.Spec
    - Test.Hspec.Core.Hooks
    - Test.Hspec.Core.Runner
    - Test.Hspec.Core.Format
    - Test.Hspec.Core.Formatters
    - Test.Hspec.Core.Formatters.V1
    - Test.Hspec.Core.Formatters.V2
    - Test.Hspec.Core.QuickCheck
    - Test.Hspec.Core.Util

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      hspec-meta: *version
      silently: ">= 1.2.4"
      QuickCheck: ">= 2.14"
      process:
      temporary:
      base-orphans:
    build-tools: hspec-meta:hspec-meta-discover
