name: hspec-core
version: 2.7.4
synopsis: A Testing Framework for Haskell
description: >
  This package exposes internal types and functions that can be used to extend
  Hspec's functionality.
copyright:
  - (c) 2011-2019 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
maintainer: Simon Hengel <sol@typeful.net>
category: Testing
stability: experimental
homepage: http://hspec.github.io/

github: hspec/hspec/hspec-core

ghc-options: -Wall

dependencies:
  - base >= 4.5.0.0 && < 5
  - random
  - tf-random
  - setenv
  - ansi-terminal >= 0.5
  - clock >= 0.7.1
  - transformers >= 0.2.2.0
  - deepseq
  - HUnit == 1.6.*
  - QuickCheck >= 2.13.1
  - quickcheck-io >= 0.2.0
  - hspec-expectations == 0.8.2.*
  - call-stack
  - directory
  - filepath

  - stm >= 2.2 # for asyc
  - array # for Diff

source-dirs:
  - src
  - vendor

library:
  exposed-modules:
    - Test.Hspec.Core.Spec
    - Test.Hspec.Core.Hooks
    - Test.Hspec.Core.Runner
    - Test.Hspec.Core.Formatters
    - Test.Hspec.Core.QuickCheck
    - Test.Hspec.Core.Util

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec-meta >= 2.3.2
      - silently >= 1.2.4
      - QuickCheck >= 2.14
      - process
      - temporary
    build-tools: hspec-meta:hspec-meta-discover
