name: api-check

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  api-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cabal/store
          key: api-check-${{ github.run_id }}
          restore-keys: api-check-

      - run: cabal update
      - run: mkdir -p $HOME/.local/bin/
      - working-directory: util/api-dump/
        run: cabal install --installdir=$HOME/.local/bin/

      - run: util/dump-api

      - name: Check for uncommitted changes
        run: git diff --quiet || (git diff && false)
